services:
  coturn:
    image: coturn/coturn:4.6.2-alpine
    container_name: expresso_ice_coturn
    restart: unless-stopped
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "10000-10100:10000-10100/udp"

    environment:
      TURN_SECRET: "${TURN_SECRET}"      
      TURN_USER:   "${TURN_USER}"        
      TURN_PWD:    "${TURN_PASSWORD}"    
      TURN_REALM:  "${TURN_REALM}"       
      TURN_EXTERNAL_IP: "${TURN_EXTERNAL_IP}"  

    command: >
      --no-cli                       
      --realm=${TURN_REALM}
      --listening-port=3478
      --tls-listening-port=5349
      --external-ip=${TURN_EXTERNAL_IP}
      --listening-ip=0.0.0.0

      --min-port=10000
      --max-port=10100

      --lt-cred-mech              
      --user=${TURN_USER}:${TURN_PASSWORD}

      --no-tls                      
      --no-dtls

      --verbose
    networks:
      - expresso_ice_network

networks:
  expresso_ice_network:
    driver: bridge
